name: Upload SAM package
description: Packages and uploads a SAM template to S3

inputs:
  artifact-bucket-name:
    description: The name of the artifact S3 bucket
    required: true
  signing-profile-name:
    description: The name of the Signing Profile
    required: true
  working-directory:
    description: The working directory containing the SAM app
    required: false
  template-file:
    description: The path to the application CloudFormation template relative to the working directory
    required: false
    default: template.yaml
  version-number:
    description: The version number of the application being deployed
    required: false

runs:
  using: composite
  steps:
    - name: Upload SAM package
      working-directory: ${{ inputs.working-directory }}
      env:
        VERSION: ${{ inputs.version-number }}
        TEMPLATE_FILE: ${{ inputs.template-file }}
        SIGNING_PROFILE: ${{ inputs.signing-profile-name }}
        ARTIFACT_BUCKET: ${{ inputs.artifact-bucket-name }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      run: ${{ github.action_path }}/scripts/upload.sh
      shell: bash
