name: Terraform Artifact Publisher
description: Packages, signs and uploads Terraform configurations to S3 for secure infra pipelines.

inputs:
  aws-role-arn:
    description: The ARN of the AWS role to assume. Available output from infrastructre pipeline stack.
    required: false
  aws-region:
    description: The AWS region to use
    required: false
    default: eu-west-2
  artifact-bucket-name:
    description: The name of the artifact S3 bucket. Available output from infrastructre pipeline stack.
    required: true
  artifact-bucket-prefix:
    description: The path at which the artifact should be placed within the S3 bucket
    required: false
  checkout-repo:
    description: Check out the repo as the first step of the action. Defaults to "true".
    type: boolean
    required: false
    default: true
  signing-kms-key-arn:
    description: The ARN of the Signing KMS Key. This will be used to sign the artifact. If not provided, the artifact will be uploaded without signing.
    required: false
  signing-profile-name:
    description: The name of the Signing Profile. This has been deprecated and will be removed in a future release. Please use 'signing-kms-key-arn' instead.
  source-path:
    description: Path to the directory containing Terraform configuration files to package, sign and upload.
    required: false
    default: ./terraform
  terraform-module-path:
    description: Subdirectory within source-path that contains the Terraform module to be deployed. Defaults to source-path.
    required: false
  github-token:
    description: The token to authenticate to the GitHub API used when downloading Terraform modules from private One Login repositories.
    required: false
  terraform-version:
    description: The version of Terraform to use. Defaults to latest.
    required: false
    default: latest

runs:
  using: composite
  steps:
    - name: Checkout Repository
      if: ${{ inputs.checkout-repo == 'true' }}
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}
        role-session-name: github-actions-${{ github.sha }}

    - name: Deprecated Signing Profile Check
      if: ${{ inputs.signing-profile-name }}
      shell: bash
      run: |
        echo "::warning::⚠️ 'signing-profile-name' is deprecated and will be removed in a future release! Please use 'signing-kms-key-arn' instead."
    - name: Execute Packaging, Signing, and Upload
      shell: bash
      run: ${{ github.action_path }}/../scripts/upload.terraform.sh
      env:
        SOURCE_PATH: ${{ inputs.source-path }}
        ARTIFACT_BUCKET: ${{ inputs.artifact-bucket-name }}
        ARTIFACT_PREFIX: ${{ inputs.artifact-bucket-prefix }}
        SIGNING_KMS_KEY_ARN: ${{ inputs.signing-kms-key-arn || inputs.signing-profile-name }}
        HEAD_MESSAGE: ${{ github.event.head_commit.message }}
        COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, ' | ') }}
        COMMIT_SHA: ${{ github.event.head_commit.id }}
        TF_MODULE_PATH: ${{ inputs.terraform-module-path || inputs.source-path }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
