name: Terraform Artifact Publisher
description: "Packages, signs and uploads Terraform configurations to S3 for secure infra pipelines."

inputs:
  aws-role-arn:
    description: The ARN of the AWS role to assume
    required: false
  aws-region:
    description: The AWS region to use
    required: false
    default: eu-west-2
  artifact-bucket-name:
    description: The name of the artifact S3 bucket
    required: true
  artifact-bucket-prefix:
    description: The path at which the artifact should be placed within the S3 bucket
    required: false
  signing-profile-name:
    description: The name of the Signing Profile
    required: false
  working-directory:
    description: The working directory containing terraform
    required: false
    default: ./terraform

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}
        role-session-name: github-actions-${{ github.sha }}

    - name: Execute Packaging, Signing, and Upload
      shell: bash
      run: ${{ github.action_path }}/../scripts/upload.terraform.sh
      env:
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
        ARTIFACT_BUCKET: ${{ inputs.artifact-bucket-name }}
        ARTIFACT_PREFIX: ${{ inputs.artifact-bucket-prefix }}
        SIGNING_PROFILE: ${{ inputs.signing-profile-name }}
        HEAD_MESSAGE: ${{ github.event.head_commit.message }}
        COMMIT_SHA: ${{ github.event.head_commit.id }}
