---
swagger: "2.0"
info:
  version: "1.0"
  title: "demo-sam-app"
basePath: "/Prod"
schemes:
- "https"
paths:
  /hello:
    get:
      responses: {}
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}:HelloWorldFunction/invocations
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /hello2:
    get:
      responses: {}
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction2.Arn}/invocations
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
