name: Run act

on:
  workflow_dispatch:
  push:

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  check-actions:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Install act
        run: curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash

      - name: Run act
        run: ./bin/act -W './.github/workflows/upload-lambda.yaml'